### ISSUE TITLE
Any way to disable the banner part?

### ISSUE THREAD

**Issue by Eneswar** [ElsaTam/obsidian-fancy-a-story#16]
Great theme! I use the banner from this snippet https://publish.obsidian.md/slrvb-docs/ITS+Theme/Image+Adjustments and the theme breaks it, and I would like to keep using that, any way to do that?

**Comment by ElsaTam** [comment]
Hi! Thanks for reporting this incompatibility. I made a change and pushed a new release, it should be fixed if you update the theme :)

**Comment by Eneswar** [comment]
Awesome, I updated it but it doesnt appear to be fully compatible. |banner alone works fine but |banner+small or |banner+tall does not work. Also it looks like it broke centering images. Normally I use a snippet to center my images but both that and the one in style settings doesnt work.

**Comment by ElsaTam** [comment]
My bad, I should have read the snippet doc more carefully. I will include the banner+small, banner+tall and sban attributes to the fix.
For the image centering, it works on my side. But it does only in reading mode. Are you expecting it to work in editing mode? If yes, can you send the snippet you are currently using? I will try to see how to make it compatible with the theme.

**Comment by Eneswar** [comment]
Yea I almost never use reading view, only editing view and my snippet worked fine before the update just now. So disabling the one in style settings and using my snippet no longer work.

```css
img {
        display: block !important;
        margin-left: auto !important;
        margin-right: auto !important;
}
    
 .markdown-source-view.mod-cm6 .cm-content > * {
        margin: auto auto !important;
}
```
