### ISSUE TITLE
Theme prevents image captions

### ISSUE THREAD

**Issue by kazi-kavish** [ElsaTam/obsidian-fancy-a-story#19]
**Setup (please complete the following information)**
- OS: Linux
- Obsidian version: 1.8.7 
- Installer version: 1.8.7
- Theme version: 2.1.1

**Describe the bug**
Captions do not get displayed underneath the image.

**To Reproduce**
- Install the [Image Converter](https://github.com/xRyul/obsidian-image-converter) (v 1.3.9) or [Image Captions](https://github.com/alangrainger/obsidian-image-captions) (v 1.1.5) plugin
- For _Image Converter_, enable captions in plugin settings and reload Obsidian 
- Add a caption to an image embedded in a note - it won't show up
- Now change theme to 'Default' - caption will be visible
- Try cycling through all themes installed in your vault (using the 'Change Theme' command), caption will show for all themes except 'Fancy a Story'

**Additional context**
The _Image Converter_ and _Image Captions_ plugin work by reading the image alt-text into the `::after` pseudo class. It seems when FAS theme is enabled, CSS is unable to read the alt-text from the image.

The DOM nodes which display the image and the caption:
```HTML
<span alt="Test Caption" src="test-image.png" class="internal-embed media-embed image-embed is-loaded">
    ::before
    <img alt="Test Caption" src="app://6c2c33b32e25bfa163babdec9b5404b4a0c3/<vault>/test-image.png?1740942496267">
    ::after
</span>
``` 
CSS rules applied to the `::after` pseudo-class
```CSS
.image-captions-enabled .image-embed[alt]:after {
    display: block;
    width: var(--img-width);
    font-family: var(--font-interface);
    font-size: var(--font-smaller);
    color: var(--text-gray);
    background-color: transparent;
    opacity: 1;
    content: attr(alt);
    margin-top: 4px;
    padding: 2px 4px;
    border-radius: 0;
    font-style: italic;
    font-weight: normal;
    text-transform: none;
    letter-spacing: normal;
    border: none;
    text-align: center;
    transition: all 0.2s ease;
    box-sizing: border-box;
}
```
