### ISSUE TITLE
The effect of CSS on Android phones

### ISSUE THREAD

**Issue by cx-233** [ElsaTam/obsidian-fancy-a-story#25]
**Setup (please complete the following information)**
- OS: Android
- Obsidian version: 1.8.10
- Installer version: 1.8.10
- Theme version: 2.2.8

**Describe the bug**
The effect of Conversaiton on Android phones is different from that on computers

**To Reproduce**
I use the same callout clip on my phone and on my computer, both from the example clip, the effect is different, I don't know if the mobile terminal can achieve the effect on the computer side.

**Screenshots**
Android:
![Image](https://github.com/user-attachments/assets/0639b040-5bfe-4772-9551-ddbe76ae50ae)

Windows:
![Image](https://github.com/user-attachments/assets/b1e77105-5c39-496a-943e-f17dad4640f7)

**Additional context**
Many CSS works differently on mobile phones than on computers, so do you think about optimizing them in the future?

**Comment by ElsaTam** [comment]
Hi. Thanks for reporting.

Unfortunately, I am not able to reproduce. The conversation snippet works correctly on my phone, I see no difference with the computer version. I am on the same Android version, and the same Obsidian version too, so I really don't know what is going on. Same thing happened a few days ago with another report about a difference between mobile and PC that I was not able to reproduce.

In your case, I think that the HSL relative color might not be supported. It's what allows me to compute two slightly different colors for the left and the right side of the conversation. And that would explain why the only difference is those colors not applying.

I can suggest a few "testing" snippets that you can try and screenshot me the results. It's going to be a little bit shots in the dark, so I'm not sure it will bring a solution. If you're willing to do that (the easiest would be through the plugin `CSS Editor`), here are a few one that you can try (you don't need to test them all, just test them in order and if one create visible results, send me the corresponding screenshot):
```css
.callout[data-callout="conversation"] {
    --complementary-color-odd: green;
    --complementary-color-even: purple;
    --line-color-odd: color-mix(in srgb, rgb(var(--conversation-color)), var(--complementary-color-odd) 15%);
    --line-color-even: color-mix(in srgb, rgb(var(--conversation-color)), var(--complementary-color-even) 15%);
}
```

```css
.callout[data-callout="conversation"] {
    --line-color-odd: pink;
    --line-color-even: cyan;
}
```

```css
.callout[data-callout="conversation"] > .callout-content > * {
    background: pink !important;
}
```

If none of this work, debugging will become quite complex. You would need to do multiple steps to be able to access the dev tool and look for more info that would help me debug. If you're interested, you can find more info here: https://docs.obsidian.md/Plugins/Getting+started/Mobile+development#Android

---

> Many CSS works differently on mobile phones than on computers, so do you think about optimizing them in the future?

If you're talking about performance optimization, that's not something I will be able to do, I'm afraid. Unless you can precisely pin point the issue, I won't be able to guess what part of the code creates performance drops, since I don't have any on my side.

If you're talking about optimizing the look so that they are identical, it's also a little bit complex. As you see in the conversation issue, I can't reproduce on my side and therefore I have to "guess" what's wrong. You provided the information about the conversation callout being different, so I know this one causes an issue. And if my guess is right, I will be able to fix every other place where I use relative HSL color.
But that might not cover everything and you would need to send me an exhaustive list of the issues you see in order for me to work on them. And you would also need to try out things since I can't properly "test" on my side (because I have no issue for starting) :/ So it would be cumbersome. But I'm willing to do it if you are too :)
