### ISSUE TITLE
Blank Screen After Creating a New Note

### ISSUE THREAD

**Issue by Nicolas-Gatien** [ElsaTam/obsidian-fancy-a-story#9]
After creating a new vault and installing this theme, upon creating a new note, Obsidian turns grey and I need to close and reopen it before seeing the new note.

Here is what it looks like:
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/22ad7920-fa33-450b-827d-ae708ad2450b">

This happens when I click the new note button, or ctrl + click on a note that is yet to be created but is linked somewhere else.

The console DevTools are also disconnected when this happens:
<img width="530" alt="image" src="https://github.com/user-attachments/assets/bcbe343c-72de-4fcd-81e3-e42f90da23b5">

Let me know if there's any other information I can provide that would be helpful.

**Comment by Nicolas-Gatien** [comment]
No need to apologize, just reporting on the issue so I can help in the development of this theme. :D

@ElsaTam this is a new vault with no community plugins - I disabled as many core plugins as I could, keeping files, graph view and search - and I'm still getting the same issue.

I tried loading the sandbox vault and installing the theme. Upon creating a note I got the same issue.

Any other ideas for how I can further diagnose this?

**Comment by Nicolas-Gatien** [comment]
Current version is v1.7.7

@ElsaTam the bug continued to occur until I removed this block of CSS (lines 1227 to 1238):
```css
@container style(--font-text-override: "??") {
  .app-container {
    --font-weight: var(--font-light);
  }
  .markdown-source-view,
  .markdown-source-view.mod-cm6 .cm-scroller,
  .markdown-preview-view,
  .community-modal-readme,
  .sync-history-preview {
    font-weight: var(--font-weight);
  }
}
```

Once I remove this block, I can create new notes without any problems.
